apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "audit-service"
  description: Microservice for auditing activities
  tags:
    - java
spec:
  type: service
  owner: user:guest
  lifecycle: production
